language: rust
rust:
  - 1.35.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

dependencies:
  cache_directories:
    - kcov-36
  override:
    - |
      if [[ ! -d "kcov-36" ]]; then
        wget 'https://github.com/SimonKagstrom/kcov/archive/v36.zip' -O /tmp/kcov.zip
        unzip /tmp/kcov.zip
        cd kcov-36
        cmake .
        make -j$(nproc)
      else
        cd kcov-36
      fi
      sudo make install

install:
  - cargo install cargo-kcov

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - g++
      - pkg-config
      - jq
      - binutils-dev
      - libiberty-dev

after_success: |
  cargo kcov --coveralls