language: rust
rust:
  - 1.35.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

install:
  - cargo install cargo-kcov
  - cargo kcov --print-install-kcov-sh | sh
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - install
      - cmake
      - g++
      - pkg-config jq
      - binutils-dev
      - libiberty-dev

after_success: |
  cargo kcov --coveralls